/*
Deployment script for C:\USERS\CMACIVOR\DOCUMENTS\VISUAL STUDIO 2013\PROJECTS\YLFR\YLFR\APP_DATA\MENTORSHIPAPPLLICANTS.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\CMACIVOR\DOCUMENTS\VISUAL STUDIO 2013\PROJECTS\YLFR\YLFR\APP_DATA\MENTORSHIPAPPLLICANTS.MDF"
:setvar DefaultFilePrefix "C_\USERS\CMACIVOR\DOCUMENTS\VISUAL STUDIO 2013\PROJECTS\YLFR\YLFR\APP_DATA\MENTORSHIPAPPLLICANTS.MDF_"
:setvar DefaultDataPath "C:\Users\cmacivor\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\cmacivor\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to ApplicantId';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[HowDidYouHere] (SqlSimpleColumn) will not be renamed to HowDidYouHear';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[TimeCommitment] (SqlSimpleColumn) will not be renamed to TimeCommitmentDays';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[BackgroundCheck] (SqlSimpleColumn) will not be renamed to SSN';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Applicant]...';


GO
CREATE TABLE [dbo].[Applicant] (
    [ApplicantId]                       INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]                         NVARCHAR (50)  NOT NULL,
    [MiddleName]                        NVARCHAR (50)  NOT NULL,
    [LastName]                          NVARCHAR (50)  NOT NULL,
    [Date]                              DATETIME2 (7)  NOT NULL,
    [Address]                           NVARCHAR (50)  NOT NULL,
    [Phone]                             NCHAR (10)     NOT NULL,
    [BirthDate]                         DATETIME2 (7)  NOT NULL,
    [Gender]                            NCHAR (10)     NOT NULL,
    [Employer]                          NVARCHAR (50)  NOT NULL,
    [BusinessPhone]                     NCHAR (10)     NOT NULL,
    [Email]                             NVARCHAR (50)  NOT NULL,
    [HighestLevelEducation]             NVARCHAR (50)  NOT NULL,
    [AdvancedEducation]                 NVARCHAR (100) NOT NULL,
    [EmergencyContactName]              NVARCHAR (75)  NOT NULL,
    [EmergencyContactRelationship]      NVARCHAR (50)  NOT NULL,
    [EmergencyContactPhone]             NCHAR (10)     NOT NULL,
    [HowDidYouHear]                     NVARCHAR (500) NOT NULL,
    [WhyAreYouInterested]               NVARCHAR (500) NOT NULL,
    [PreviousVolunteerExperience]       NVARCHAR (500) NOT NULL,
    [HobbiesTalentSkills]               NVARCHAR (500) NOT NULL,
    [CommunityChurchAffiliations]       NVARCHAR (500) NOT NULL,
    [HaveYouBeenArrested]               NCHAR (10)     NOT NULL,
    [WhatWasTheCharge]                  NVARCHAR (100) NOT NULL,
    [DrivingViolation]                  NCHAR (10)     NOT NULL,
    [DrivingViolationCharge]            NVARCHAR (100) NOT NULL,
    [FacebookRegistered]                NCHAR (10)     NOT NULL,
    [MayWeInvite]                       NCHAR (10)     NOT NULL,
    [DoYouHaveTransportation]           NCHAR (10)     NOT NULL,
    [ProvideRide]                       NCHAR (10)     NOT NULL,
    [TimeCommitmentDays]                INT            NOT NULL,
    [TimeCommitmentTimes]               INT            NOT NULL,
    [AreasOfInterest]                   INT            NOT NULL,
    [AreaOfInterestOther]               NVARCHAR (250) NOT NULL,
    [LearningCenterPreference]          INT            NOT NULL,
    [StatementSignature]                BIT            NOT NULL,
    [VolunteerCoordinator]              NCHAR (10)     NOT NULL,
    [StatementSignatureDate]            DATETIME2 (7)  NOT NULL,
    [VolunteerCoordinatorDate]          DATETIME2 (7)  NOT NULL,
    [ConfidentialityStatementSignature] BIT            NOT NULL,
    [AbusePolicySignature]              BIT            NOT NULL,
    [PublicityPreferences]              INT            NOT NULL,
    [PublicitySignature]                BIT            NOT NULL,
    [SSN]                               NCHAR (15)     NOT NULL,
    [City]                              NVARCHAR (50)  NULL,
    [State]                             NCHAR (10)     NOT NULL,
    [Zip]                               NCHAR (10)     NOT NULL,
    [County]                            NVARCHAR (50)  NULL,
    [DLState]                           NCHAR (10)     NULL,
    [DL#]                               NVARCHAR (50)  NULL,
    [BackgroundCheckSignature]          BIT            NULL,
    PRIMARY KEY CLUSTERED ([ApplicantId] ASC)
);

CREATE TABLE [dbo].[CommitmentDays] (
    [TimeCommitmentDayId] INT           IDENTITY (1, 1) NOT NULL,
    [ApplicantID]         INT           NOT NULL,
    [TimeCommitmentDay]   NVARCHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([TimeCommitmentDayId] ASC)
);

alter table CommitmentDays
add constraint fk_CommitmentDays
foreign key (ApplicantID)
references Applicant(ApplicantId)

CREATE TABLE [dbo].[CommitmentTimes]
(
	[CommitmentTimeID] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
    [ApplicantID] INT NOT NULL, 
    [CommitmentTime] NVARCHAR(50) NOT NULL,
	Constraint fk_CommitmentTimes FOREIGN KEY (ApplicantID)
	REFERENCES Applicant (ApplicantId)
)

CREATE TABLE [dbo].[InterestAreas]
(
	[InterestAreaID] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
    [ApplicantID] INT NOT NULL, 
    [InterestArea] NVARCHAR(30) NOT NULL,
	Constraint fk_InterestArea FOREIGN KEY (ApplicantID)
	REFERENCES Applicant (ApplicantId)
)

CREATE TABLE [dbo].[LearningCenterPreferences]
(
	[LearningCenterPreferenceID] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
    [ApplicantID] INT NOT NULL, 
    [LearningCenterPreference] NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_LearningCenterPreference FOREIGN KEY (ApplicantID)
	REFERENCES Applicant(ApplicantId)
)


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
