//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLFR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public Applicant()
        {
            this.CommitmentDays = new HashSet<CommitmentDay>();
            this.CommitmentTimes = new HashSet<CommitmentTime>();
            this.InterestAreas = new HashSet<InterestArea>();
            this.LearningCenterPreferences = new HashSet<LearningCenterPreference>();
        }
    
        public int ApplicantId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Date { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string Employer { get; set; }
        public string BusinessPhone { get; set; }
        public string Email { get; set; }
        public string HighestLevelEducation { get; set; }
        public string AdvancedEducation { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string HowDidYouHear { get; set; }
        public string WhyAreYouInterested { get; set; }
        public string PreviousVolunteerExperience { get; set; }
        public string HobbiesTalentSkills { get; set; }
        public string CommunityChurchAffiliations { get; set; }
        public string HaveYouBeenArrested { get; set; }
        public string WhatWasTheCharge { get; set; }
        public string DrivingViolation { get; set; }
        public string DrivingViolationCharge { get; set; }
        public string FacebookRegistered { get; set; }
        public string MayWeInvite { get; set; }
        public string DoYouHaveTransportation { get; set; }
        public string ProvideRide { get; set; }
        public Nullable<int> TimeCommitmentDays { get; set; }
        public Nullable<int> TimeCommitmentTimes { get; set; }
        public Nullable<int> AreasOfInterest { get; set; }
        public string AreaOfInterestOther { get; set; }
        public Nullable<int> LearningCenterPreference { get; set; }
        public Nullable<bool> StatementSignature { get; set; }
        public string VolunteerCoordinator { get; set; }
        public Nullable<System.DateTime> StatementSignatureDate { get; set; }
        public Nullable<System.DateTime> VolunteerCoordinatorDate { get; set; }
        public Nullable<bool> ConfidentialityStatementSignature { get; set; }
        public Nullable<bool> AbusePolicySignature { get; set; }
        public Nullable<int> PublicityPreferences { get; set; }
        public Nullable<bool> PublicitySignature { get; set; }
        public string SSN { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string DLState { get; set; }
        public string DL_ { get; set; }
        public Nullable<bool> BackgroundCheckSignature { get; set; }
    
        public virtual ICollection<CommitmentDay> CommitmentDays { get; set; }
        public virtual ICollection<CommitmentTime> CommitmentTimes { get; set; }
        public virtual ICollection<InterestArea> InterestAreas { get; set; }
        public virtual ICollection<LearningCenterPreference> LearningCenterPreferences { get; set; }
    }
}
